### ISSUE TITLE
Changed username and app did not generate

### ISSUE THREAD

**Issue by OnCoreliu1** [OnCoreliu1/PublicRobo1#11]

**Comment by philiprbrenan** [comment]
I imagine that I have to reset the web hook connecting you to coreliu.org and perhaps do other things,  I will be working on this right now.

**Comment by philiprbrenan** [comment]
Was the name before the rename:

  ExperiDev1
  CoreliuOrg

?

**Comment by OnCoreliu1** [comment]
My username was GforC1. Now it is OnCoreliu1. You have fixed issue I think as the app is playing. Thank you.
